import type { MetricDefinition } from "@/models";

export const METRIC_DEFINITIONS: MetricDefinition[] = [
  {
    type: "temperature",
    label: "Temperature",
    unit: "°C",
    icon: "thermometer",
    inputType: "numeric",
    min: 34,
    max: 42,
    placeholder: "e.g. 37.2",
    color: "#EF4444",
  },
  {
    type: "weight",
    label: "Weight",
    unit: "kg",
    icon: "activity",
    inputType: "numeric",
    min: 20,
    max: 300,
    placeholder: "e.g. 72.5",
    color: "#8B5CF6",
  },
  {
    type: "heart_rate",
    label: "Heart Rate",
    unit: "bpm",
    icon: "heart",
    inputType: "numeric",
    min: 30,
    max: 220,
    placeholder: "e.g. 72",
    color: "#EC4899",
  },
  {
    type: "bp_systolic",
    label: "BP Systolic",
    unit: "mmHg",
    icon: "trending-up",
    inputType: "numeric",
    min: 60,
    max: 250,
    placeholder: "e.g. 120",
    color: "#F59E0B",
  },
  {
    type: "bp_diastolic",
    label: "BP Diastolic",
    unit: "mmHg",
    icon: "trending-down",
    inputType: "numeric",
    min: 40,
    max: 150,
    placeholder: "e.g. 80",
    color: "#F97316",
  },
  {
    type: "blood_oxygen",
    label: "Blood Oxygen",
    unit: "%",
    icon: "droplet",
    inputType: "numeric",
    min: 70,
    max: 100,
    placeholder: "e.g. 98",
    color: "#3B82F6",
  },
  {
    type: "blood_sugar",
    label: "Blood Sugar",
    unit: "mg/dL",
    icon: "zap",
    inputType: "numeric",
    min: 40,
    max: 600,
    placeholder: "e.g. 95",
    color: "#10B981",
  },
  {
    type: "pain_level",
    label: "Pain Level",
    unit: "/10",
    icon: "alert-circle",
    inputType: "scale",
    min: 0,
    max: 10,
    placeholder: "0–10",
    color: "#EF4444",
  },
  {
    type: "sleep_hours",
    label: "Sleep",
    unit: "hrs",
    icon: "moon",
    inputType: "numeric",
    min: 0,
    max: 24,
    placeholder: "e.g. 7.5",
    color: "#6366F1",
  },
  {
    type: "water_intake",
    label: "Water Intake",
    unit: "L",
    icon: "droplet",
    inputType: "numeric",
    min: 0,
    max: 10,
    placeholder: "e.g. 2.0",
    color: "#06B6D4",
  },
  {
    type: "steps",
    label: "Steps",
    unit: "steps",
    icon: "navigation",
    inputType: "numeric",
    min: 0,
    max: 100000,
    placeholder: "e.g. 8000",
    color: "#84CC16",
  },
  {
    type: "note",
    label: "Custom Note",
    unit: "",
    icon: "edit-3",
    inputType: "text",
    placeholder: "Write anything...",
    color: "#64748B",
  },
];

export function getMetricDef(type: string): MetricDefinition | undefined {
  return METRIC_DEFINITIONS.find((m) => m.type === type);
}

export const MOOD_LABELS: Record<number, { label: string; emoji: string; color: string }> = {
  1: { label: "Very Bad", emoji: "😞", color: "#EF4444" },
  2: { label: "Bad", emoji: "😕", color: "#F97316" },
  3: { label: "Okay", emoji: "😐", color: "#F59E0B" },
  4: { label: "Good", emoji: "🙂", color: "#84CC16" },
  5: { label: "Great", emoji: "😊", color: "#10B981" },
};
